"""Initial workflow schema

Revision ID: 017cfc4e40bc
Revises: 
Create Date: 2026-04-25 15:09:03.987140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017cfc4e40bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('specification', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_specs'))
    )
    op.create_index(op.f('ix_workflow_specs_created_at'), 'workflow_specs', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_specs_id'), 'workflow_specs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_specs_priority'), 'workflow_specs', ['priority'], unique=False)
    op.create_index(op.f('ix_workflow_specs_spec_id'), 'workflow_specs', ['spec_id'], unique=True)
    op.create_index(op.f('ix_workflow_specs_status'), 'workflow_specs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_specs_title'), 'workflow_specs', ['title'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='executionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('agents_used', sa.JSON(), nullable=True),
    sa.Column('tasks_count', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spec_id'], ['workflow_specs.id'], name=op.f('fk_workflow_executions_spec_id_workflow_specs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_executions'))
    )
    op.create_index(op.f('ix_workflow_executions_completed_at'), 'workflow_executions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_workflow_executions_execution_id'), 'workflow_executions', ['execution_id'], unique=True)
    op.create_index(op.f('ix_workflow_executions_id'), 'workflow_executions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_phase'), 'workflow_executions', ['phase'], unique=False)
    op.create_index(op.f('ix_workflow_executions_spec_id'), 'workflow_executions', ['spec_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_started_at'), 'workflow_executions', ['started_at'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('agent_assigned', sa.String(length=100), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], name=op.f('fk_workflow_tasks_execution_id_workflow_executions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_tasks'))
    )
    op.create_index(op.f('ix_workflow_tasks_completed_at'), 'workflow_tasks', ['completed_at'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_created_at'), 'workflow_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_execution_id'), 'workflow_tasks', ['execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_id'), 'workflow_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_started_at'), 'workflow_tasks', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_task_id'), 'workflow_tasks', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_tasks_task_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_started_at'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_execution_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_created_at'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_completed_at'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_workflow_executions_started_at'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_spec_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_phase'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_execution_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_completed_at'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_workflow_specs_title'), table_name='workflow_specs')
    op.drop_index(op.f('ix_workflow_specs_status'), table_name='workflow_specs')
    op.drop_index(op.f('ix_workflow_specs_spec_id'), table_name='workflow_specs')
    op.drop_index(op.f('ix_workflow_specs_priority'), table_name='workflow_specs')
    op.drop_index(op.f('ix_workflow_specs_id'), table_name='workflow_specs')
    op.drop_index(op.f('ix_workflow_specs_created_at'), table_name='workflow_specs')
    op.drop_table('workflow_specs')
    # ### end Alembic commands ###
